Feat: 콜백 단건 조회 로직 개선
kakao-tech-campus-2nd-step3/Team8_BE pull request #123
Opened 2024-10-30 03:19 UTC by zzoe2346

## #️⃣ 연관된 이슈
> ex) #이슈번호, #이슈번호

#119

## 📝 작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요.(이미지 첨부 가능)

### 상태에 따른 검증 로직 추가
변경된 코드에서는 먼저 callback의 status가 WAITING인지 확인합니다.
만약 WAITING 상태가 아닌 경우, callback.getAssignedMemberId()가 null이 아니고, memberId와 일치하는지 확인하여 해당 콜백이 할당된 사용자만 접근할 수 있도록 제한.

개선점: WAITING이 아닌 상태에서는 오직 할당된 시니또만 접근할 수 있도록 하였습니다!

### 예외 처리 추가
WAITING 상태가 아니면서 할당된 사용자가 아닌 경우, ForbiddenException을 발생시키도록 했습니다.

개선점: 대기 중이 아닌 콜백에 대해 권한이 없는 멤버가 접근하려 할 때 예외를 던지는 로직 추가.

### 버그 수정
기존에 callback 엔티티에서 `Long assignedMemberId = null`(아직 대기중인 할당되지 않은 콜백) 때문에 대기중인 콜백을 조회시 .NullPointerException 이 발생하여 500 응답에러가 발생하였습니다. null 처리가 미흡하여 발생한 버그로 파악되었습니다. null 처리에 대한 로직 추가하여 해결하였습니다.

> 상황별 테스트 추가

> 스웨거에서 정상적으로 동작되는거 확인 완료
### 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

## ⏰ 현재 버그

## ✏ Git Close
> close #이슈번호
> 
 
close #119

2024-10-30 12:31 UTC, eunsoni requested changes
리뷰 하나 남겼습니다!

2024-10-30 12:31 UTC, eunsoni commented on src/main/java/com/example/sinitto/callback/service/CallbackService.java
> +            if (callback.getAssignedMemberId() != null && callback.getAssignedMemberId().equals(memberId)) {
callback.getAssignedMemberId().equals(memberId) 이 조건을 만족한다면 callback.getAssignedMemberId()이 null일 수 없고 "callback.getAssignedMemberId() != null" 를 무조건 만족하기 때문에  이 조건은 빼도 같은 로직으로 작동하지 않을까요?

` if (callback.getAssignedMemberId().equals(memberId)) {`

2024-10-30 13:10 UTC, zzoe2346 commented on src/main/java/com/example/sinitto/callback/service/CallbackService.java
> +            if (callback.getAssignedMemberId() != null && callback.getAssignedMemberId().equals(memberId)) {
의견 감사드립니다! 사실 수정 전에는 은선님이 제안주신 코드를 사용하였었는데 NullPointException 이 발생해서 수정하게되었습니다. 예외 발생의 이유를 설명드리자면


**가정**: callback 은 아직 할당이 안되어 `assignedMemberId = null` 인 상황
`callback.getAssignedMemberId().equals(memberId)` 이것만 있을경우, `callback.getAssignedMemberId()` 이 `null`이라서 `null.equals(memberId)` 가 되어 `NullPointException` 이 발생하는것으로 파악이 됩니다. 

그래서 `callback.getAssignedMemberId() != null `로 미리 null을 확인하여 예외 발생을 방지해 보았습니다!

callback.getAssignedMemberId() 는 null 이 있는 경우가 많기때문에
![SCR-20241030-tdbh](https://github.com/user-attachments/assets/06fe5a2f-db5a-4ab1-b6be-69bd8899942b)
![SCR-20241030-tdoh](https://github.com/user-attachments/assets/6de8999b-87cb-4460-a547-58f59befe7c6)

위 테스트 코드를 돌리면 아래와 같은 예외가 발생

2024-10-30 15:24 UTC, eunsoni commented on src/main/java/com/example/sinitto/callback/service/CallbackService.java
> +            if (callback.getAssignedMemberId() != null && callback.getAssignedMemberId().equals(memberId)) {
아하 그런 이유가 있었네요~
예외 상황을 정확히 파악하고 수정하셨네요!😊

2024-10-30 15:24 UTC, eunsoni approved these changes
수고하셨습니다:>

2024-10-30 15:43 UTC, GitJIHO approved these changes
좋은 개선점이라 생각합니다! 추후에 안부전화 로직에도 적용을 고려해봐야겠네요 :)
고생하셨습니다 👍

2024-10-31 02:08 UTC, 2iedo approved these changes
수정된 부분 확인했습니다! 고생하셨어요~

2024-10-31 02:10 UTC, merged